FROM python:2.7

ENV JENKINSMETA_ENV="development"
ENV JENKINSMETA_WORKSPACE="/jenkinsmeta"
ENV JENKINSMETA_EXEC="python $JENKINSMETA_WORKSPACE/app.py"

RUN mkdir -p $JENKINSMETA_WORKSPACE
COPY . $JENKINSMETA_WORKSPACE

RUN pip install -r $JENKINSMETA_WORKSPACE/requirements/$JENKINSMETA_ENV.txt

CMD $JENKINSMETA_EXEC
